// 운영자 에디터: 로그인 → 기존 시나리오 열람 → 새 3인 시나리오 작성(캐릭터/설정집/단서 이미지/진행흐름/구역) → 저장 → 게임 선반 반영
import { launch, sleep, shots, URL } from './lib.mjs';
import { io } from 'socket.io-client';
let fails = 0;
const check = (c, m) => { console.log(c ? '  ✔' : '  ✘', m); if (!c) fails++; };
const b = await launch();
const ctx = await b.newContext({ viewport: { width: 1440, height: 900 } });
const p = await ctx.newPage();
p.on('pageerror', (e) => console.log('pageerror', e.message));
p.on('dialog', (d) => d.accept());
await p.goto(`${URL}/admin`);
await p.fill('input[type=password]', 'wrong');
await p.click('button[type=submit]');
await sleep(400);
check(await p.$('.form-error'), '틀린 운영자 비밀번호 거부');
const api401 = await (await fetch(`${URL}/api/admin/scenarios`)).status;
check(api401 === 401, '토큰 없이 운영자 API 접근 불가 (401)');
await p.fill('input[type=password]', 'midnight-admin');
await p.click('button[type=submit]');
await p.waitForSelector('.ed-shell');
await p.click('.ed-list li:has-text("해무관")');
await p.waitForSelector('.ed-tabs');
await sleep(300);
await p.screenshot({ path: `${shots}/50-editor-basic.png` });
check((await p.textContent('.ed-issues .head')).includes('플레이 가능'), '테스트 시나리오: 검증 통과 표시');
await p.click('.ed-tabs button:has-text("진행 흐름")');
await p.click('.ed-card.step:has-text("현장 조사") header');
await sleep(300);
await p.screenshot({ path: `${shots}/51-editor-flow.png` });
await p.click('.ed-tabs button:has-text("밀담 구역")');
await sleep(500);
await p.screenshot({ path: `${shots}/52-editor-zones.png` });

// 새 시나리오
await p.click('text=＋ 새 시나리오');
await p.waitForSelector('.ed-tabs');
const idInput = p.locator('.ed-field:has-text("시나리오 ID") input');
await idInput.fill('trio-test');
await p.locator('.ed-field:has-text("제목") input').first().fill('세 사람의 밀실');
await p.locator('.ed-field:has-text("최대 인원") input').fill('3');
await p.locator('.ed-field:has-text("최소 인원") input').fill('3');
await p.click('.ed-field:has-text("공개 여부") input[type=checkbox]');
await sleep(200);
check((await p.textContent('.ed-issues .head')).includes('오류'), '인원 3명인데 캐릭터 2명 → 오류 감지');
await p.click('.ed-tabs button:has-text("캐릭터")');
await p.click('text=＋ 캐릭터 추가');
await sleep(200);
await p.locator('.ed-card.open .ed-field:has-text("이름") input').first().fill('인물 C');
// 단서 + 이미지 업로드
await p.click('.ed-tabs button:has-text("단서")');
await p.click('text=＋ 단서 추가');
await p.locator('.ed-card.open .ed-field:has-text("제목") input').fill('찢어진 사진');
await p.locator('.ed-card.open .ed-field:has-text("종류") select').selectOption('image');
const fileInput = await p.$('.ed-card.open input[type=file]');
await fileInput.setInputFiles('data/uploads/haemugwan/cover.svg');
await p.waitForSelector('.ed-card.open .ed-image img', { timeout: 5000 });
check(true, '단서 이미지 업로드');
await p.locator('.ed-card.open .ed-field:has-text("공개 범위") select').selectOption('private');
await p.click('.ed-card.open .ed-check:has-text("인물 C")');
// 진행 흐름: 공개 이벤트에 단서 추가, 투표 후보에 인물 C 추가
await p.click('.ed-tabs button:has-text("진행 흐름")');
await p.click('.ed-card.step:has-text("프롤로그와 설정집") header');
await p.click('.pick:has-text("찢어진 사진") input');
await p.click('.pick:has-text("새 인물 — 설정집") input').catch(() => {});
await sleep(200);
const recText = await p.textContent('.pick:has-text("찢어진 사진")');
check(recText.includes('→ 인물 C'), `개인 단서 실제 수신자 미리보기: ${recText.trim().slice(-12)}`);
await p.click('.ed-card.step:has-text("범인 지목") header');
await p.click('.ed-card.step.open .ed-check:has-text("인물 C")').catch(() => {});
// 새 구역: 빈 곳 드래그
await p.click('.ed-tabs button:has-text("밀담 구역")');
const stage = await p.$('.zone-stage');
const sb = await stage.boundingBox();
await p.mouse.move(sb.x + sb.width * 0.42, sb.y + sb.height * 0.80);
await p.mouse.down();
await p.mouse.move(sb.x + sb.width * 0.52, sb.y + sb.height * 0.92, { steps: 8 });
await p.mouse.up();
await sleep(300);
const zoneCount = await p.$$eval('.zone-rect', (e) => e.length);
check(zoneCount === 5, `드래그로 새 구역 생성 (${zoneCount}개)`);
await p.locator('.zone-side .ed-field:has-text("구역 이름") input').fill('고해실');
// 밀담 구역에는 인원 제한이 없다 — 관련 입력란이 남아 있지 않은지 확인한다
check(!(await p.$('.zone-side .ed-check:has-text("인원 제한")')), '구역 인원 제한 입력란이 없음');
await p.screenshot({ path: `${shots}/53-editor-newzone.png` });
const head = await p.textContent('.ed-issues .head');
check(head.includes('플레이 가능'), `수정 후 검증 통과: ${head}`);
if (!head.includes('플레이 가능')) console.log(await p.textContent('.ed-issues ul'));
await p.keyboard.press('Control+s');
await sleep(800);
const status = await p.textContent('.ed-top .small');
check(status.includes('저장됨'), `저장: ${status}`);

// 게임 선반 반영 확인 (서버 재시작 없이)
const s = io(URL, { transports: ['websocket'] });
await new Promise((r) => s.on('connect', r));
await new Promise((r) => s.emit('auth', { nickname: '확인' }, r));
const list = await new Promise((r) => s.emit('rooms:list', r));
const found = list.modules[0].contents.find((c) => c.contentId === 'trio-test');
check(found && found.minPlayers === 3, '저장 즉시 게임 선반에 3인 시나리오 등장');
s.disconnect();
console.log(fails ? `\n실패 ${fails}건` : '\n에디터 검사 모두 통과');
await b.close();
process.exit(fails ? 1 : 0);
