import { launch, sleep, shots, URL } from './lib.mjs';
const b = await launch();
const ctx = await b.newContext({ viewport: { width: 1440, height: 900 } });
const p = await ctx.newPage();
p.on('pageerror', (e) => console.log('pageerror', e.message));
p.on('console', (m) => { if (m.type() === 'error') console.log('console', m.text()); });
await p.goto(URL);
await p.waitForSelector('#nick');
await sleep(800);
await p.screenshot({ path: `${shots}/01-title.png` });
await p.fill('#nick', '탐정A');
await p.click('button[type=submit]');
await p.waitForSelector('.lobby-screen');
await sleep(600);
await p.screenshot({ path: `${shots}/02-lobby.png` });
await p.click('text=＋ 방 만들기');
await p.waitForSelector('.modal');
await p.click('.modal button[type=submit]');
await p.waitForSelector('.room-screen', { timeout: 8000 });
await sleep(1500);
await p.screenshot({ path: `${shots}/03-room.png` });
await b.close();
